version: "3.5"
services:
  blockchain:
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    networks:
      - blockchain
    volumes:
      - ./blockchain/data:/data
  scan:
    build:
      context: ./blockchain
      dockerfile: BlockExplorerDockerfile
    ports:
      - "8000:8000"
    depends_on:
      - blockchain
    networks:
      - blockchain

  tdc21:
    build:
      context: ./TDC21
      dockerfile: Dockerfile
    image: tdc21
    depends_on:
      - blockchain
    volumes:
      - ./TDC21/src:/app
    networks:
      - blockchain

networks:
  blockchain:
    name: blockchain
