version: "3.5"
services:
  blockchain:
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    networks:
      - blockchain
  scan:
    build:
      context: ./blockchain
      dockerfile: BlockExplorerDockerfile
    ports:
      - "8000:8000"
    depends_on:
      - blockchain
    networks:
      - blockchain

networks:
  blockchain:
    name: blockchain
