version: "3.5"
services:
  blockchain:
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    networks:
      - blockchain
  scan:
    image: carechain/eth-explorer
    ports:
      - "8000:8000"
    environment:
      - GETH_HOSTNAME=blockchain
      - GETH_RPCPORT=8545
    depends_on:
      - blockchain
    networks:
      - blockchain

  tdc21:
    build:
      context: ./TDC21
      dockerfile: Dockerfile
    image: tdc21
    depends_on:
      - blockchain
    volumes:
      - ./TDC21/src:/app
    networks:
      - blockchain

networks:
  blockchain:
    name: blockchain
