# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Solidity contracts CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Run Test Chain
      working-directory: ./TDC21/src
      run: |
          npm i ganache-cli
          node_modules/.bin/ganache-cli -e 1000 &
          
    - name: Install Dependencies
      working-directory: ./TDC21/src
      run: |
          npm i truffle
          npm i
          
    - name: Test
      working-directory: ./TDC21/src
      run: |
          node_modules/.bin/truffle test --network ci
